### ISSUE TITLE
Error message - Warning: substr_count() expects parameter 1 to be string

### ISSUE THREAD

**Issue by CyberKatsu** [muckypuddle/joomla-tags-selected#4]
Hi there,

I have installed this module and tried to order by date created (which I couldnt do with lasinducharith's version).

I am getting an error message on top of the module :
"Warning: substr_count() expects parameter 1 to be string, array given in /home/USER/public_html/WEBSITE/libraries/cms/helper/tags.php on line 511".

I have tried on J3.3.6 and a new J3.4 install with the same result.

Not sure if I have misconfigured or whether there is a conflict anywhere.

**Comment by paul-muckypuddle** [comment]
Hi,

This is expected behaviour within Joomla / PHP. The file referenced in that warning message is not part of this module - it's a core Joomla file, and you can ignore the error.

This looks like a bit of a bug within Joomla tbh - the core code is trying to count the number of tags, but it's passing an array to the PHP function instead of a string. See around line 494 in http://developer.joomla.org/cms-coverage/libraries_cms_helper_tags.php.html

**Comment by CyberKatsu** [comment]
Thanks for the explanation. I see what you mean now. I'm amazed that your extension is not part of core Joomla. The features it provides are more important than the core "tag cloud" module in my opinion, and it gives a lot more flexibility compared to the "article category" module.

**Comment by paul-muckypuddle** [comment]
To be honest I love tags but I had the same feeling as yourself - tag functionality isn't much use if there's not an equivalent (or better) to mod_articles_category for tags.

I'll perhaps propose getting this module integrated into the core for a future release (though tbh I'm not sure how I'd get that process kicked off...)
